///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class CartModelProducts {
/*
{
  "productId": 1,
  "quantity": 4
}
*/

  int? productId;
  int? quantity;

  CartModelProducts({
    this.productId,
    this.quantity,
  });
  CartModelProducts.fromJson(Map<String, dynamic> json) {
    productId = json['productId']?.toInt();
    quantity = json['quantity']?.toInt();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['productId'] = productId;
    data['quantity'] = quantity;
    return data;
  }
}

class CartModel {
/*
{
  "id": 1,
  "userId": 1,
  "date": "2020-03-02T00:00:00.000Z",
  "products": [
    {
      "productId": 1,
      "quantity": 4
    }
  ],
  "__v": 0
}
*/

  int? id;
  int? userId;
  String? date;
  List<CartModelProducts?>? products;

  CartModel({
    this.id,
    this.userId,
    this.date,
    this.products,
  });
  CartModel.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    userId = json['userId']?.toInt();
    date = json['date']?.toString();
    if (json['products'] != null) {
      final v = json['products'];
      final arr0 = <CartModelProducts>[];
      v.forEach((v) {
        arr0.add(CartModelProducts.fromJson(v));
      });
      products = arr0;
    }
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['userId'] = userId;
    data['date'] = date;
    if (products != null) {
      final v = products;
      final arr0 = [];
      v!.forEach((v) {
        arr0.add(v!.toJson());
      });
      data['products'] = arr0;
    }
    return data;
  }
}
